#!/bin/bash

export MPIENV_ROOT="$(cd "$(dirname "${BASH_SOURCE:-$0}")"; pwd)"

if [ ! -f $MPIENV_ROOT/shims ]; then
    G=$MPIENV_ROOT/version_global
    if [ -f $G ]; then
        ln -s $(cat $G) $MPIENV_ROOT/shims
    fi
fi

export PATH=$MPIENV_ROOT/shims/bin:${PATH:-}
export LD_LIBRARY_PATH=$MPIENV_ROOT/shims/lib:$MPIENV_ROOT/shims/lib64:${LD_LIBRARY_PATH:-}

function usage() {
    echo "Usage: mpienv [command] [options...]"
}

function mpienv() {
    if [ "0" = "${#*}" ]; then
        usage
        return -1
    fi

    declare -r root=$MPIENV_ROOT
    declare -r command="$1"
    shift

    case "$command" in
        "use" )
            {
                eval $(env PYTHONPATH=$MPIENV_ROOT:${PYTHONPATH:-} \
                           python $root/bin/use.py $*)
                if [ -z "${BASH_VERSION:-}" -a ! -z "${ZSH_VERSION:-}" ]; then
                    rehash
                fi
            }
            ;;
        "install" )
            {
                env PYTHONPATH=$MPIENV_ROOT:${PYTHONPATH:-} \
                    python $root/bin/install.py $*
            }
            ;;
        "add" )
            {
               env PYTHONPATH=$MPIENV_ROOT:${PYTHONPATH:-} \
                   python $root/bin/add.py $*
            }
            ;;
        "rm" )
            {
                env PYTHONPATH=$MPIENV_ROOT:${PYTHONPATH:-} \
                    python $root/bin/rm.py $*
            }
            ;;
        "rename" )
            {
                env PYTHONPATH=$MPIENV_ROOT:${PYTHONPATH:-} \
                    python $root/bin/rename.py $*
            }
            ;;
        "list" )
            {
                env PYTHONPATH=$MPIENV_ROOT:${PYTHONPATH:-} \
                    python $root/bin/list.py $*
            }
            ;;
        "info" )
            {
                env PYTHONPATH=$MPIENV_ROOT:${PYTHONPATH:-} \
                    python $root/bin/info.py $*
            }
            ;;
        "autodiscover" )
            {
                env PYTHONPATH=$MPIENV_ROOT:${PYTHONPATH:-} \
                    python $root/bin/autodiscover.py $*
            }
            ;;
        "prefix" )
            {
                env PYTHONPATH=$MPIENV_ROOT:${PYTHONPATH:-} \
                    python $root/bin/prefix.py $*
            }
            ;;
        * )
            echo "mpienv [ERROR]: Unknown command '$command'"
            ;;
    esac
}
