#!/bin/bash

export PATH=$HOME/.mpienv/shims/bin:$PATH
export LD_LIBRARY_PATH=$HOME/.mpienv/shims/lib:$HOME/.mpienv/shims/lib64:$LD_LIBRARY_PATH

function mpienv() {
    command="$1"
    shift

    case "$command" in
        "use" )
            {
                python ~/.mpienv/mpienv_use.py $*
            }
            ;;
        "list" )
            {
                python ~/.mpienv/mpienv_list.py $*
            }
            ;;
        "info" )
            {
                python ~/.mpienv/mpienv_info.py $*
            }
            ;;
        * )
            echo "mpienv [ERROR]: Unknown command '$command'"
            ;;
    esac
}
